## Problem 1: Geocode shopping centers (7 points)

The overall aim of problems 1-3 is to find out **how many people live within a walking distance (1.5 km) from certain shopping centres in Helsinki**.

Problem 1 concerns the locations of shopping centres: find their addresses and translate them into coordinates.

---

### a) Prepare an input file containing the addresses of shopping centres (2 point)

Find out the addresses of the following shopping centres (e.g., by using your favourite search engine), and collect them in a text file called `shopping_centres.txt`:

 - Itis
 - Forum
 - Iso-omena
 - Sello
 - Jumbo
 - REDI
 - Tripla 
 
The text file should be in semicolon-separated format (`;`) and include the following columns:

- `id` (integer) a unique identifier for each shopping centre (a
- `name` (string) of each shopping center
- `addr` (string) the address 


See an example of how to format the text file [in the lesson 3 materials](https://autogis-site.readthedocs.io/en/latest/lessons/lesson-3/geocoding-in-geopandas.html). Remember to *add*, *commit*, and *push* the file to your git repository.

---

### b) Read the list of addresses (1 point)

Read the list of addresses you just prepared into a `pandas.DataFrame` called `shopping_centres`

In [1]:
# Import Libraries
import pathlib
import pandas as pd

# Data Directory and Notebook Path
NOTEBOOK_PATH = pathlib.Path().resolve()
DATA_DIRECTORY = NOTEBOOK_PATH / "data"

# Read File
shopping_centres = pd.read_csv(
    DATA_DIRECTORY / "shopping_centres.txt",
    sep = ";"
)

shopping_centres.head(7)

     id       name                                            addr
0  1000       Itis            Itäkatu 1-7, 00930 Helsinki, Finland
1  1001      Forum  Mannerheimintie 14–20, 00100 Helsinki, Finland
2  1002  Iso-omena           Piispansilta 11, 02230 Espoo, Finland
3  1003      Sello       Leppävaarankatu 3-9, 02600 Espoo, Finland
4  1004      Jumbo      Vantaanportinkatu 3, 01510 Vantaa, Finland
5  1005       REDI   Hermannin rantatie 5, 00580 Helsinki, Finland
6  1006     Tripla      Fredikanterassi 1, 00520 Helsinki, Finland

In [2]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
import pandas
assert isinstance(shopping_centres, pandas.DataFrame)
for column in ("id", "name", "addr"):
    assert column in shopping_centres.columns


---

### c) Geocode the addresses (3 points)

Geocode the addresses using the Nominatim geocoding service. Join the results with the input data, and store them in a `geopandas.GeoDataFrame` with the same name (`shopping_centres`). 

Remember to define a custom `user_agent` string!

In [3]:
import geopandas

# Geocode addresses - Nominatim geocoding service
geocoded = geopandas.tools.geocode(
    shopping_centres["addr"],
    provider="nominatim",
    user_agent="autogis2025",
    timeout=10
)

# Join geometries to DataFrame
shopping_centres = geopandas.GeoDataFrame(
    shopping_centres.join(geocoded[["geometry"]]),
    geometry = "geometry")
    

shopping_centres.head(8)

,id,name,addr,geometry
0,1000,Itis,"Itäkatu 1-7, 00930 Helsinki, Finland",POINT (25.08036 60.21034)
1,1001,Forum,"Mannerheimintie 14–20, 00100 Helsinki, Finland",POINT (24.93781 60.16903)
2,1002,Iso-omena,"Piispansilta 11, 02230 Espoo, Finland",POINT (24.73834 60.16129)
3,1003,Sello,"Leppävaarankatu 3-9, 02600 Espoo, Finland",POINT (24.80836 60.21818)
4,1004,Jumbo,"Vantaanportinkatu 3, 01510 Vantaa, Finland",POINT (24.96568 60.29159)
5,1005,REDI,"Hermannin rantatie 5, 00580 Helsinki, Finland",POINT (24.97895 60.18673)
6,1006,Tripla,"Fredikanterassi 1, 00520 Helsinki, Finland",POINT (24.93250 60.19882)

In [4]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
import geopandas
assert isinstance(shopping_centres, geopandas.GeoDataFrame)
for column in ("id", "name", "addr", "geometry"):
    assert column in shopping_centres.columns

Check that the coordinate reference system of the geocoded result is correctly defined, and **reproject the layer into ETRS GK-25** (EPSG:3879):

In [5]:
# CRS Check
geocoded.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [6]:
# Reproject the Layer into ETRS  GK-25
shopping_centres = shopping_centres.to_crs(epsg=3879)

In [7]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
import pyproj
assert shopping_centres.crs == pyproj.CRS("EPSG:3879")


---

### d) Save the resulting vector data set (1 point)

Save `shopping_centres` as a *GeoPackage* named `shopping_centres.gpkg`:

In [8]:
# ADD YOUR OWN CODE HERE
shopping_centres.to_file(DATA_DIRECTORY / "shopping_centres.gpkg")


---

Well done! Now you can continue to [problem 2](Exercise-3-Problem-2.ipynb)